apiVersion: v1
kind: Service
metadata:
  name: svc-user
  labels:
    app: svc-user
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32702
  selector:
    app: pod-user-management