apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configmap
  namespace: default
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
  KC_DB_URL_HOST: "postgresql-service"
  KC_DB_URL_DATABASE: "keycloak"
  KC_DB_USERNAME: "keycloak"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"